---
- name: "Add GPG key(s) to apt"
  apt_key:
    url: "{{ item.key }}"
    state: present
  with_items: "{{ configure_kubernetes_repository[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] | json_query('apt_repository[].gpgkey[]') }}"
  when:
    - "configure_kubernetes_repository[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] | json_query('apt_repository[].gpgkey[]') is not none"
  tags:
    - "kubernetes-repository"
- name: "Add GPG key(s) to rpm"
  rpm_key:
    fingerprint: "{{ item.fingerprint }}"
    key: "{{ item.key }}"
    state: present
  with_items: "{{ configure_kubernetes_repository[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] | json_query('yum_repository[].gpgkey[]') }}"
  when:
    - "configure_kubernetes_repository[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] | json_query('yum_repository[].gpgkey[]') is not none"
  tags:
    - "kubernetes-repository"
- name: "Add apt repository(s)"
  apt_repository:
    repo: "{{ item.repo }}"
    state: "present"
  with_items: "{{ configure_kubernetes_repository[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)].apt_repository | default([]) }}"
  tags:
    - "kubernetes-repository"
- name: "Add yum repository(s)"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl}}"
    repo_gpgcheck: "{{ item.repo_gpgcheck }}"
    gpgkey: "{{ item.gpgkey[0].key }}"
  with_items: "{{ configure_kubernetes_repository[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)].yum_repository | default([]) }}"
  tags:
    - "kubernetes-repository"
